apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-react-app
  template:
    metadata:
      labels:
        app: test-react-app
    spec:
      containers:
      - name: test-react-app
        # image: skbilal1236/test-react-app:latest
        image: react-app-test-image:latest
        ports:
        - containerPort: 5000
