apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test_react_app
  template:
    metadata:
      labels:
        app: test_react_app
    spec:
      containers:
      - name: test_react_app
        # image: skbilal1236/test_react_app:latest
        image: React-App-Test:latest
        ports:
        - containerPort: 5000
