apiVersion: v1
kind: Service
metadata:
  name: test-react-app-service
spec:
  selector:
    app: test-react-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 6000
    nodePort: 31110
